import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawn } from 'node:child_process';
import { parse } from './parser.js';
import { compile } from './compiler.js';

const TARGETS = new Set(['web', 'backend', 'native']);

export async function buildTarget(source, target, { outDir, appName = 'cannon-app' } = {}) {
  if (!TARGETS.has(target)) throw new Error(`unsupported Cannon target: ${target}`);
  if (!outDir) throw new Error('buildTarget requires outDir');
  const root = path.resolve(outDir);
  await fs.rm(root, { recursive: true, force: true });
  await fs.mkdir(root, { recursive: true });

  const sourceDigest = sha256(source);
  const files = [];
  if (target === 'web') {
    const { code } = compile(source);
    const app = `globalThis.__CANNON_TARGET__ = 'web';\n${code}`;
    const html = `<!doctype html>\n<html><head><meta charset="utf-8"><title>${escapeHtml(appName)}</title></head><body><script type="module" src="./app.mjs"></script></body></html>\n`;
    await write(root, 'app.mjs', app, files);
    await write(root, 'index.html', html, files);
  } else if (target === 'backend') {
    const { code } = compile(source);
    const app = `globalThis.__CANNON_TARGET__ = 'backend';\n${code}`;
    await write(root, 'server.mjs', app, files);
  } else {
    const ast = parse(source);
    const c = emitNativeC(ast);
    await write(root, 'main.c', c, files);
  }

  const manifest = {
    protocol: 'cannon-target/1',
    appName,
    target,
    sourceDigest,
    files: files.map(({ path: file, digest, bytes }) => ({ path: file, digest, bytes }))
  };
  manifest.digest = sha256(canonical(manifest));
  await fs.writeFile(path.join(root, 'cannon-build.json'), JSON.stringify(manifest, null, 2) + '\n', 'utf8');
  return { root, manifest };
}

export async function executeTarget(build, { cc = process.env.CC || 'cc', timeoutMs = 10_000 } = {}) {
  const { root, manifest } = build;
  if (manifest.target === 'web') {
    return runProcess(process.execPath, [path.join(root, 'app.mjs')], { timeoutMs });
  }
  if (manifest.target === 'backend') {
    return runProcess(process.execPath, [path.join(root, 'server.mjs')], { timeoutMs });
  }
  if (manifest.target === 'native') {
    const binary = path.join(root, process.platform === 'win32' ? 'cannon-app.exe' : 'cannon-app');
    const compiled = await runProcess(cc, [path.join(root, 'main.c'), '-std=c11', '-O2', '-o', binary], { timeoutMs });
    if (!compiled.ok) return { ok: false, stage: 'compile', compile: compiled };
    const executed = await runProcess(binary, [], { timeoutMs });
    return { ...executed, stage: 'execute', compile: compiled, binary };
  }
  throw new Error(`unknown built target: ${manifest.target}`);
}

export async function reproducibleTargetBuild(source, target, options = {}) {
  const first = await buildTarget(source, target, { ...options, outDir: path.join(options.root ?? process.cwd(), '.cannon-proof-a') });
  const second = await buildTarget(source, target, { ...options, outDir: path.join(options.root ?? process.cwd(), '.cannon-proof-b') });
  return {
    reproducible: first.manifest.digest === second.manifest.digest,
    first: first.manifest,
    second: second.manifest
  };
}

export async function benchmarkCompiler(source, { iterations = 100, warmup = 10 } = {}) {
  if (!Number.isInteger(iterations) || iterations < 1) throw new RangeError('iterations must be a positive integer');
  for (let i = 0; i < warmup; i++) compile(source);
  const durations = [];
  for (let i = 0; i < iterations; i++) {
    const start = process.hrtime.bigint();
    compile(source);
    durations.push(Number(process.hrtime.bigint() - start) / 1e6);
  }
  const sorted = [...durations].sort((a, b) => a - b);
  const total = durations.reduce((sum, value) => sum + value, 0);
  return {
    iterations,
    meanMs: total / iterations,
    medianMs: percentile(sorted, 0.5),
    p95Ms: percentile(sorted, 0.95),
    minMs: sorted[0],
    maxMs: sorted.at(-1),
    sourceBytes: Buffer.byteLength(source)
  };
}

export function emitNativeC(ast) {
  const declarations = collectTopLevelDeclarations(ast);
  const functions = ast.body.filter((node) => node.type === 'FunctionDeclaration');
  const topLevel = ast.body.filter((node) => node.type !== 'FunctionDeclaration');
  const lines = [
    '/* Generated by Cannon native target */',
    '#include <stdint.h>',
    '#include <stdio.h>',
    '#include <string.h>',
    ''
  ];
  for (const fn of functions) lines.push(emitCFunction(fn), '');
  lines.push('int main(void) {');
  for (const declaration of declarations) lines.push(`  int64_t ${declaration} = 0;`);
  for (const statement of topLevel) lines.push(...emitCStatement(statement, 1, new Set(declarations)));
  lines.push('  return 0;', '}', '');
  return lines.join('\n');
}

function emitCFunction(node) {
  const params = node.params.map((name) => `int64_t ${name}`).join(', ') || 'void';
  const declared = new Set(node.params);
  const locals = collectBlockDeclarations(node.body).filter((name) => !declared.has(name));
  const lines = [`int64_t ${node.name}(${params}) {`];
  for (const name of locals) { lines.push(`  int64_t ${name} = 0;`); declared.add(name); }
  for (const statement of node.body.body) lines.push(...emitCStatement(statement, 1, declared));
  lines.push('  return 0;', '}');
  return lines.join('\n');
}

function emitCStatement(node, level, declared) {
  const pad = '  '.repeat(level);
  switch (node.type) {
    case 'VariableDeclaration':
      declared.add(node.name);
      return [`${pad}${node.name} = ${emitCExpression(node.value)};`];
    case 'AssignmentStatement': {
      const prefix = declared.has(node.name) ? '' : 'int64_t ';
      declared.add(node.name);
      return [`${pad}${prefix}${node.name} = ${emitCExpression(node.value)};`];
    }
    case 'ReturnStatement': return [`${pad}return ${node.value ? emitCExpression(node.value) : '0'};`];
    case 'ExpressionStatement': {
      if (node.expression.type === 'CallExpression' && node.expression.callee.type === 'Identifier' && node.expression.callee.name === 'print') {
        const [value] = node.expression.arguments;
        if (value?.type === 'Literal' && typeof value.value === 'string') return [`${pad}puts(${cString(value.value)});`];
        return [`${pad}printf("%lld\\n", (long long)(${emitCExpression(value)}));`];
      }
      return [`${pad}(void)(${emitCExpression(node.expression)});`];
    }
    case 'IfStatement': {
      const out = [`${pad}if (${emitCExpression(node.test)}) {`];
      for (const statement of node.consequent.body) out.push(...emitCStatement(statement, level + 1, declared));
      out.push(`${pad}}`);
      if (node.alternate) {
        if (node.alternate.type === 'IfStatement') {
          const nested = emitCStatement(node.alternate, level, declared);
          out[out.length - 1] += ' else ' + nested[0].trimStart();
          out.push(...nested.slice(1));
        } else {
          out[out.length - 1] += ' else {';
          for (const statement of node.alternate.body) out.push(...emitCStatement(statement, level + 1, declared));
          out.push(`${pad}}`);
        }
      }
      return out;
    }
    case 'WhileStatement': {
      const out = [`${pad}while (${emitCExpression(node.test)}) {`];
      for (const statement of node.body.body) out.push(...emitCStatement(statement, level + 1, declared));
      out.push(`${pad}}`);
      return out;
    }
    case 'BlockStatement': {
      const out = [`${pad}{`];
      for (const statement of node.body) out.push(...emitCStatement(statement, level + 1, declared));
      out.push(`${pad}}`);
      return out;
    }
    default: throw new Error(`native target does not support statement ${node.type}`);
  }
}

function emitCExpression(node) {
  switch (node?.type) {
    case 'Literal':
      if (typeof node.value === 'number') return Number.isFinite(node.value) ? String(Math.trunc(node.value)) : '0';
      if (typeof node.value === 'boolean') return node.value ? '1' : '0';
      if (node.value === null) return '0';
      if (typeof node.value === 'string') throw new Error('native string values are currently supported only as direct print arguments');
      break;
    case 'Identifier': return node.name;
    case 'UnaryExpression': return `(${node.operator}${emitCExpression(node.argument)})`;
    case 'BinaryExpression': {
      const operator = node.operator === '==' ? '==' : node.operator === '!=' ? '!=' : node.operator;
      return `(${emitCExpression(node.left)} ${operator} ${emitCExpression(node.right)})`;
    }
    case 'CallExpression':
      if (node.callee.type !== 'Identifier') throw new Error('native target requires identifier callees');
      return `${node.callee.name}(${node.arguments.map(emitCExpression).join(', ')})`;
  }
  throw new Error(`native target does not support expression ${node?.type ?? 'unknown'}`);
}

function collectTopLevelDeclarations(ast) {
  const functions = new Set(ast.body.filter((node) => node.type === 'FunctionDeclaration').map((node) => node.name));
  const names = new Set();
  for (const node of ast.body) {
    if (node.type === 'VariableDeclaration' || node.type === 'AssignmentStatement') names.add(node.name);
  }
  for (const name of functions) names.delete(name);
  return [...names].sort();
}

function collectBlockDeclarations(block) {
  const names = new Set();
  const visit = (node) => {
    if (node.type === 'VariableDeclaration' || node.type === 'AssignmentStatement') names.add(node.name);
    if (node.type === 'IfStatement') { for (const child of node.consequent.body) visit(child); if (node.alternate?.body) for (const child of node.alternate.body) visit(child); }
    if (node.type === 'WhileStatement' || node.type === 'BlockStatement') for (const child of node.body) visit(child);
  };
  for (const statement of block.body) visit(statement);
  return [...names].sort();
}

async function write(root, relative, content, files) {
  const target = path.join(root, relative);
  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, content, 'utf8');
  files.push({ path: relative.replace(/\\/g, '/'), digest: sha256(content), bytes: Buffer.byteLength(content) });
}

function runProcess(bin, args, { timeoutMs }) {
  return new Promise((resolve, reject) => {
    const child = spawn(bin, args, { stdio: 'pipe' });
    let stdout = '', stderr = '';
    child.stdout.setEncoding('utf8'); child.stderr.setEncoding('utf8');
    child.stdout.on('data', (chunk) => stdout += chunk);
    child.stderr.on('data', (chunk) => stderr += chunk);
    child.once('error', reject);
    const timer = setTimeout(() => child.kill('SIGKILL'), timeoutMs);
    child.once('close', (code, signal) => { clearTimeout(timer); resolve({ ok: code === 0, code, signal, stdout, stderr, command: { bin, args } }); });
  });
}

function canonical(value) {
  if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`;
  if (value && typeof value === 'object') return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonical(value[key])}`).join(',')}}`;
  return JSON.stringify(value);
}
function sha256(value) { return crypto.createHash('sha256').update(value).digest('hex'); }
function cString(value) { return JSON.stringify(String(value)).replace(/\\u2028|\\u2029/g, ' '); }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, (char) => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[char])); }
function percentile(sorted, q) { return sorted[Math.min(sorted.length - 1, Math.max(0, Math.ceil(sorted.length * q) - 1))]; }
